INSERT INTO SHOP.PRODUCTS (IDENTIFIER, NAMES, PRIME) VALUES (1, 'dota', 1000);
INSERT INTO SHOP.PRODUCTS (IDENTIFIER, NAMES, PRIME) VALUES (2, 'csgo', 150);
INSERT INTO SHOP.PRODUCTS (IDENTIFIER, NAMES, PRIME) VALUES (3, 'honor 8x', 15499);
INSERT INTO SHOP.PRODUCTS (IDENTIFIER, NAMES, PRIME) VALUES (4, 'honor 9x lite', 22999);
INSERT INTO SHOP.PRODUCTS (IDENTIFIER, NAMES, PRIME) VALUES (5, 'amazfit', 5499);
INSERT INTO SHOP.PRODUCTS (IDENTIFIER, NAMES, PRIME) VALUES (6, 'milk', 89);
INSERT INTO SHOP.PRODUCTS (IDENTIFIER, NAMES, PRIME) VALUES (7, 'slack', 1541);
INSERT INTO SHOP.PRODUCTS (IDENTIFIER, NAMES, PRIME) VALUES (8, 'tiktok', 1542);